### ISSUE TITLE
Infinite loop is possible for banners slider????????????????????????????????

### ISSUE THREAD

**Issue by hemanthsp** [uiuniversal/ngu-carousel#17] opened 2018-02-23 13:19 UTC
Infinite loop is possible for banners slider?

**Comment by hemanthsp** [comment] 2018-03-01 06:15
give me any suggestion i will also try

**Comment by sheikalthaf** [comment] 2018-09-30 14:07
@fridolin-koch Hi,

Do you have any idea to make the carousel loop?

**Comment by xXCalleManXx** [comment] 2020-04-30 12:29
Any solution for this?

**Comment by santoshyadavdev** [comment] 2022-12-25 21:48
duplicate of  https://github.com/uiuniversal/ngu-carousel/issues/7

**Closed by santoshyadavdev** 2022-12-25 21:48 UTC
Labels: Feature request, accepting-prs
