### ISSUE TITLE
found version 4, expected 3

### ISSUE THREAD

**Issue by missaouiaymen** [uiuniversal/ngu-carousel#131] opened 2018-12-14 16:11 UTC
ERROR in Error: Metadata version mismatch for module 
.../node_modules/@ngu/carousel/ngu-carousel.d.ts, found version 4, expected 3, resolving symbol AppModule in /app.module.ts

**Comment by sheikalthaf** [comment] 2018-12-16 05:05
@missaouiaymen looking weird. never faced this kind of issue. any reproducing steps

**Comment by roik7** [comment] 2018-12-26 14:44
@missaouiaymen -  did you manage to run it?
@sheikalthaf -  having the same issue
my angular version: 4.1.3
basically did the same thing WillHall recommended in issue: https://github.com/sheikalthaf/ngu-carousel/issues/128
and than I get the following error:
node_modules/@ngu/carousel/ngu-carousel.d.ts, found version 4, expected 3, resolving symbol AppModule

**Comment by sheikalthaf** [comment] 2018-12-26 17:13
@missaouiaymen @roik7 The current version is only support angular version >= 6. because it is using angular 6 library building.

**Comment by roik7** [comment] 2018-12-28 01:16
@sheikalthaf - thanks for the response.
is there a prior version that does support angular 4?

**Closed** 2020-07-26 14:55 UTC
Labels: need: repo
